//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpostWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpostWeb.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesab Parametrləri.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvanlar.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ünvan.
        /// </summary>
        public static string AddressLine {
            get {
                return ResourceManager.GetString("AddressLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əlavə Et.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artıq qeydiyyatdan keçmisiniz?.
        /// </summary>
        public static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mövcudluq.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ən Çox Satılanlar.
        /// </summary>
        public static string BestSeller {
            get {
                return ResourceManager.GetString("BestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ləğv et.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoxlama.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qonaq.
        /// </summary>
        public static string CheckoutAsGuest {
            get {
                return ResourceManager.GetString("CheckoutAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yoxlanış metodu.
        /// </summary>
        public static string CheckoutMethod {
            get {
                return ResourceManager.GetString("CheckoutMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəhər.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəng.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirkət.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsdiqlə.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəni Təsdiqlə.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Davam Et.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış-verişə Davam Et.
        /// </summary>
        public static string ContinueShopping {
            get {
                return ResourceManager.GetString("ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ölkə.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni hesab yarat.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni hesabınızı yaradın.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartın nömrəsi.
        /// </summary>
        public static string CreditCardNumber {
            get {
                return ResourceManager.GetString("CreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müştəri Rəyi.
        /// </summary>
        public static string CustomerReviews {
            get {
                return ResourceManager.GetString("CustomerReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV Kodu.
        /// </summary>
        public static string CVVCode {
            get {
                return ResourceManager.GetString("CVVCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gün əvvəl.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təsvir.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detallı.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifariş keçmişinizə və statusunuza asan keçid .
        /// </summary>
        public static string EasyAccess {
            get {
                return ResourceManager.GetString("EasyAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenilə.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-poçt ünvanı.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son istifadə tarixi.
        /// </summary>
        public static string ExpiryDate {
            get {
                return ResourceManager.GetString("ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sual-cavab.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sürətli və asan yoxlama.
        /// </summary>
        public static string FastAndEasyCheckOut {
            get {
                return ResourceManager.GetString("FastAndEasyCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Önə  Çıxan Məhsullar.
        /// </summary>
        public static string FeaturedProducts {
            get {
                return ResourceManager.GetString("FeaturedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrənizi unutmusunuz.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tez-tez soruşulan suallar.
        /// </summary>
        public static string FrequentlyAskedQuestions {
            get {
                return ResourceManager.GetString("FrequentlyAskedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cəmi Qiymət.
        /// </summary>
        public static string Grandtotal {
            get {
                return ResourceManager.GetString("Grandtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qonaq və ya qeydiyyat girişi.
        /// </summary>
        public static string GuestRegisterLogin {
            get {
                return ResourceManager.GetString("GuestRegisterLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salam, hesabınıza xoş gəldiniz.
        /// </summary>
        public static string HelloWelcome {
            get {
                return ResourceManager.GetString("HelloWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Əsas.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endirimdə Olanlar.
        /// </summary>
        public static string HotDeals {
            get {
                return ResourceManager.GetString("HotDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şəkil.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ən son yeniləndi:.
        /// </summary>
        public static string LastUpdated {
            get {
                return ResourceManager.GetString("LastUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siyahı.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlar.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim Hesabım.
        /// </summary>
        public static string MyAccaunt {
            get {
                return ResourceManager.GetString("MyAccaunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səbət.
        /// </summary>
        public static string MyCart {
            get {
                return ResourceManager.GetString("MyCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mənim seçdiklərim.
        /// </summary>
        public static string MyWishlist {
            get {
                return ResourceManager.GetString("MyWishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Ünvan.
        /// </summary>
        public static string NewAddress {
            get {
                return ResourceManager.GetString("NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Məhsullar.
        /// </summary>
        public static string NewProducts {
            get {
                return ResourceManager.GetString("NewProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müqayisə ediləcək məhsul(lar) yoxdur.
        /// </summary>
        public static string NotCompare {
            get {
                return ResourceManager.GetString("NotCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səhifələr.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrə.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödəmə Metodları.
        /// </summary>
        public static string PaymentMethods {
            get {
                return ResourceManager.GetString("PaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nömrəsi.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa aşağıdan daxil olun.
        /// </summary>
        public static string PleaseLoginBelow {
            get {
                return ResourceManager.GetString("PleaseLoginBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçin.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət: Yuxarıdan Aşağıya.
        /// </summary>
        public static string PriceHighLow {
            get {
                return ResourceManager.GetString("PriceHighLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət: Aşağıdan Yuxarıya .
        /// </summary>
        public static string PriceLowHigh {
            get {
                return ResourceManager.GetString("PriceLowHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət Aralığı.
        /// </summary>
        public static string PriceSlider {
            get {
                return ResourceManager.GetString("PriceSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul: A-dan Z-yə.
        /// </summary>
        public static string ProductAToZ {
            get {
                return ResourceManager.GetString("ProductAToZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulların müqayisəsi.
        /// </summary>
        public static string ProductComparison {
            get {
                return ResourceManager.GetString("ProductComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul Haqqında.
        /// </summary>
        public static string Productİnfo {
            get {
                return ResourceManager.GetString("Productİnfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsulun Adı.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsullar.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məhsul Etiketləri.
        /// </summary>
        public static string ProductTags {
            get {
                return ResourceManager.GetString("ProductTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyfiyyət.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ədəd.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyat keç.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyatdan keç və zaman qazan.
        /// </summary>
        public static string RegisterAndSaveTime {
            get {
                return ResourceManager.GetString("RegisterAndSaveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gələcəkdəki rahatlığınız üçün qeydiyyat keçin.
        /// </summary>
        public static string RegisterForFuture {
            get {
                return ResourceManager.GetString("RegisterForFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məni xatırla.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəylər.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndərilmə və vergini qeyd edin.
        /// </summary>
        public static string ShippingAndTax {
            get {
                return ResourceManager.GetString("ShippingAndTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndərilmə və vergi üçün yer seçin.
        /// </summary>
        public static string ShippingAndTaxDestination {
            get {
                return ResourceManager.GetString("ShippingAndTaxDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alış-veriş edin.
        /// </summary>
        public static string ShopBy {
            get {
                return ResourceManager.GetString("ShopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göstər.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil Olun.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qeydiyyatdan keç.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxşar Məhsullar.
        /// </summary>
        public static string SimilarProducts {
            get {
                return ResourceManager.GetString("SimilarProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sırala.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulduz.
        /// </summary>
        public static string Star {
            get {
                return ResourceManager.GetString("Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulduz.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndər.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tək Qiymət.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xülasə.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populyar Kateqoriyalar.
        /// </summary>
        public static string TopCategories {
            get {
                return ResourceManager.GetString("TopCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səbətini Yenilə.
        /// </summary>
        public static string UpdateCart {
            get {
                return ResourceManager.GetString("UpdateCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəyər.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilmişlər.
        /// </summary>
        public static string Wishlist {
            get {
                return ResourceManager.GetString("Wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öz Rəyini Bildir .
        /// </summary>
        public static string WriteReview {
            get {
                return ResourceManager.GetString("WriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adınız.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rəyiniz.
        /// </summary>
        public static string YourReview {
            get {
                return ResourceManager.GetString("YourReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Poçt kodu.
        /// </summary>
        public static string ZipPostalCode {
            get {
                return ResourceManager.GetString("ZipPostalCode", resourceCulture);
            }
        }
    }
}
